const {
  Document, Packer, Paragraph, TextRun, HeadingLevel,
  AlignmentType, ShadingType, PageBreak, convertInchesToTwip, BorderStyle,
} = require('docx');
const fs = require('fs');

const h1 = (text) => new Paragraph({
  text,
  heading: HeadingLevel.HEADING_1,
  spacing: { before: 400, after: 200 },
});
const h2 = (text) => new Paragraph({
  text,
  heading: HeadingLevel.HEADING_2,
  spacing: { before: 300, after: 160 },
});
const h3 = (text) => new Paragraph({
  text,
  heading: HeadingLevel.HEADING_3,
  spacing: { before: 240, after: 120 },
});
const p = (text) => new Paragraph({
  children: [new TextRun({ text, size: 24, font: 'Calibri' })],
  spacing: { after: 180 },
  alignment: AlignmentType.JUSTIFIED,
});
const bullet = (text, level = 0) => new Paragraph({
  children: [new TextRun({ text, size: 24, font: 'Calibri' })],
  bullet: { level },
  spacing: { after: 100 },
});
const br = () => new Paragraph({ text: '', spacing: { after: 100 } });
const pb = () => new Paragraph({ children: [new PageBreak()] });
const tip = (text) => new Paragraph({
  children: [new TextRun({ text: `TIP: ${text}`, size: 22, font: 'Calibri', italics: true, color: '1d4ed8' })],
  spacing: { before: 100, after: 100 },
  indent: { left: convertInchesToTwip(0.3) },
});
const code = (text) => new Paragraph({
  children: [new TextRun({ text, font: 'Courier New', size: 20, color: '374151' })],
  spacing: { after: 80 },
  indent: { left: convertInchesToTwip(0.4) },
  shading: { type: ShadingType.SOLID, color: 'f3f4f6', fill: 'f3f4f6' },
});
const center = (text, size = 24, bold = false, color = '0f172a') => new Paragraph({
  children: [new TextRun({ text, size, font: 'Calibri', bold, color })],
  alignment: AlignmentType.CENTER,
  spacing: { after: 200 },
});

const doc = new Document({
  title: 'ETOH Market Full Project Documentation',
  styles: {
    default: { document: { run: { font: 'Calibri', size: 24 } } },
    paragraphStyles: [
      {
        id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal',
        run: { bold: true, size: 36, color: '92400e', font: 'Calibri' },
        paragraph: { spacing: { before: 400, after: 200 },
          border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'f59e0b', space: 4 } } },
      },
      {
        id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal',
        run: { bold: true, size: 28, color: '1d4ed8', font: 'Calibri' },
        paragraph: { spacing: { before: 280, after: 140 } },
      },
      {
        id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal',
        run: { bold: true, size: 26, color: '059669', font: 'Calibri' },
        paragraph: { spacing: { before: 200, after: 100 } },
      },
    ],
  },
  sections: [{
    properties: {},
    children: [

      /* ── COVER ── */
      center('ETOH MARKET', 72, true, '92400e'),
      center('The Digital Central Market of Cameroon', 32, false, '64748b'),
      center('FULL PROJECT DOCUMENTATION', 28, true, '374151'),
      center('Written in plain English -- for everyone', 24, false, '94a3b8'),
      center('Version 1.0  -  June 2026', 22, false, '94a3b8'),
      pb(),

      /* ── CH 1 ── */
      h1('Chapter 1 -- What Is ETOH Market?'),
      p('Imagine you live in Douala, Cameroon. You want to buy a new kaba ngondo dress, but you do not know which vendor has the best price. You could spend all day walking through Marche Central in the hot sun, asking every seller. Or you could just open ETOH Market on your phone.'),
      br(),
      p('ETOH Market is a website -- like a digital version of Marche Central -- where Cameroonian sellers can put their products online, and buyers anywhere in Cameroon can find them, see the price, and contact the seller directly on WhatsApp.'),
      br(),
      p('Think of it as the meeting point between a vendor sitting in Bafoussam and a buyer sitting in Yaounde, without either of them having to travel.'),
      br(),
      h2('The Name "ETOH"'),
      p('ETOH is the Cameroonian concept of the central marketplace -- the hub of commerce, community, and connection. Just like the physical central market is the heartbeat of a Cameroonian city, ETOH Market aims to be the heartbeat of Cameroonian digital commerce.'),
      br(),
      h2('Who Is It For?'),
      bullet('Vendors (sellers) who want to show their products to more people without renting a shop'),
      bullet('Buyers who want to find products quickly, compare prices, and contact sellers safely'),
      bullet('Anyone in Cameroon who wants to do business online, simply and affordably'),
      br(),
      h2('What Can You Do On ETOH Market?'),
      bullet('Browse hundreds of products from local Cameroonian vendors'),
      bullet('Watch short video clips (Market Buzz Reels) of vendors showing their products -- like TikTok for the market'),
      bullet('Contact any vendor instantly on WhatsApp'),
      bullet('Request home delivery via a bendskin (moto taxi) rider'),
      bullet('Negotiate the price using the built-in Bargain Calculator'),
      bullet('Check today\'s market prices for common staples like tomatoes, plantains and rice'),
      bullet('Post what you\'re looking for so vendors can come to you (Je Cherche)'),
      bullet('Switch the entire website between English and French with one click'),
      br(),
      pb(),

      /* ── CH 2 ── */
      h1('Chapter 2 -- Why Did We Build This?'),
      p('Every feature on ETOH Market was built to solve a real, specific problem that Cameroonians face every day when buying and selling. This chapter explains each problem and the solution we built.'),
      br(),
      h2('Problem 1: Buyers Waste Time Walking Around Markets'),
      p('In Cameroon, if you want to buy a specific item -- say, a Samsung Galaxy phone -- you might visit 10 different vendors to compare prices. That takes time, money for transport, and a lot of energy under the sun.'),
      br(),
      p('Our Solution: A searchable online market where buyers can see all products, filter by category, city, and price -- all from their phone, in seconds.'),
      br(),
      h2('Problem 2: Sellers Cannot Reach Enough Buyers'),
      p('A vendor in Bamenda might have the freshest dried fish in the whole region, but buyers in Douala will never know about her. She cannot afford a website or a Facebook ad. She just sits and waits.'),
      br(),
      p('Our Solution: Every vendor gets a free "Stand" (their own page) where they list products with photos and videos. Anyone in Cameroon can find them just by searching.'),
      br(),
      h2('Problem 3: Nobody Trusts Online Sellers'),
      p('Mobile money scams are a real problem in Cameroon. Buyers are scared to pay someone they do not know online. "What if I send money and never receive my product?"'),
      br(),
      p('Our Solution: Three layers of trust protection:'),
      bullet('A Safety Gate that reminds buyers to always meet in public and inspect before paying'),
      bullet('A Verified Vendor Badge (Commercant Certifie - lion symbol) that admin gives to vendors who prove their identity'),
      bullet('WhatsApp-first contact -- buyers and sellers talk directly, no money changes hands on our platform'),
      br(),
      h2('Problem 4: Prices Are Hidden and Unfair'),
      p('In Cameroonian markets, prices are rarely written down. A seller might charge one price to a local and a different (higher) price to a stranger. Buyers do not know what is fair.'),
      br(),
      p('Our Solution: Two price tools:'),
      bullet('The Bargain Calculator -- shows buyers a realistic negotiation range (10%, 20%, or 30% off) based on the listed price'),
      bullet('Prix du Marche (Community Price Board) -- a real-time board where community members submit what they paid for staples today, showing Min / Average / Max prices by city'),
      br(),
      h2('Problem 5: Last-Mile Delivery Is Hard'),
      p('"The product looks great, but how do I get it delivered to my house?" In Cameroon, the answer is usually a bendskin (moto taxi) rider. But buyers have to figure out the logistics themselves.'),
      br(),
      p('Our Solution: The Bendskin Delivery Button. With one tap, the buyer gets a pre-written WhatsApp message ready to send to their regular bendskin rider -- already containing the product name, vendor location, price, and the buyer\'s delivery address.'),
      br(),
      h2('Problem 6: "I Know What I Want, But Cannot Find It"'),
      p('Sometimes a buyer needs something very specific -- "10 kg of fresh groundnuts, raw quality, before Thursday in Douala." She has to post in 5 different WhatsApp groups and wait for someone to respond.'),
      br(),
      p('Our Solution: Je Cherche (I\'m Looking For) -- a reverse marketplace page where buyers post their needs publicly. Vendors browse it and contact interested buyers directly on WhatsApp.'),
      br(),
      h2('Problem 7: You Never Know If the Seller Is Available'),
      p('You find a vendor online, you send a WhatsApp message... and you wait. The vendor is at the farm. Or sleeping. Or closed on Sundays. You wasted your time.'),
      br(),
      p('Our Solution: The Statut du Stand (Stand Availability Status). Every vendor can set their real-time status -- Open Now (green), Back Soon (yellow), or Closed (red) -- visible on their stand page and all product cards.'),
      br(),
      pb(),

      /* ── CH 3 ── */
      h1('Chapter 3 -- How the Project Is Built'),
      p('ETOH Market has three main parts that all work together:'),
      br(),
      h2('Part 1: The Database (SQLite)'),
      p('Think of the database as a giant filing cabinet. Every product, every vendor, every order, every price report -- everything is stored here as rows in a table, just like rows in an Excel spreadsheet.'),
      br(),
      p('We use a database called SQLite. It is stored as a single file called etoh.db right inside the project folder. Simple, fast, and no separate installation needed.'),
      br(),
      p('Tables in our database:'),
      bullet('users -- everyone who registered (name, email, password hash, WhatsApp)'),
      bullet('stands -- every vendor shop (name, description, city, phone, verified status, availability)'),
      bullet('products -- every item for sale (name, price, category, images, videos, description)'),
      bullet('orders -- every delivery request placed by a buyer'),
      bullet('posts -- all Market Buzz video reels'),
      bullet('price_reports -- community-submitted market prices'),
      bullet('wanted_posts -- buyer requests from the Je Cherche board'),
      br(),
      h2('Part 2: The Backend (Node.js + Express)'),
      p('The backend is like the kitchen of a restaurant. Customers never see it, but it does all the real work -- retrieving data, saving new records, checking passwords, sending responses.'),
      br(),
      bullet('Node.js -- the programming environment that runs our server code (JavaScript on the server side)'),
      bullet('Express.js -- a tool that makes it easy to create routes (URLs that do specific things)'),
      br(),
      p('The backend runs on port 3000 -- meaning it listens at http://localhost:3000 on your computer.'),
      br(),
      h2('Part 3: The Frontend (React + Vite)'),
      p('The frontend is everything the user sees and touches -- the homepage, the product cards, the buttons, the navigation bar.'),
      br(),
      bullet('React -- a popular JavaScript library that makes it easy to build interactive websites. Think of it as reusable building blocks called "components" that snap together to make a page.'),
      bullet('Vite -- a tool that takes all React code and bundles it into files the browser can understand, super fast.'),
      bullet('CSS -- the styling rules that make everything look beautiful (colors, fonts, layouts)'),
      br(),
      pb(),

      /* ── CH 4 ── */
      h1('Chapter 4 -- The Folder Structure (What Is Where)'),
      p('When you open the project folder, here is what you find and what each part does:'),
      br(),
      h2('Root Level Files'),
      code('etoh_market/'),
      code('  server.js        -- Starts the backend server (like turning on the engine)'),
      code('  app.js           -- Sets up all the routes and middleware'),
      code('  database.js      -- Creates the database and all tables'),
      code('  seed.js          -- Fills the database with sample data'),
      code('  seed_prices.js   -- Fills the Price Board with realistic CFA prices'),
      code('  package.json     -- Lists all the tools (packages) the project needs'),
      code('  .env             -- Secret settings (password, API keys) -- never share this!'),
      code('  etoh.db          -- The actual database file (all your data lives here)'),
      br(),
      h2('The Routes Folder (/routes)'),
      p('Each file handles a specific type of request -- like departments in a company:'),
      code('  auth.js      -- Login, registration, profile updates'),
      code('  stands.js    -- Create, view, edit, delete stands'),
      code('  products.js  -- Add, view, delete products'),
      code('  posts.js     -- Market Buzz video reels'),
      code('  orders.js    -- Delivery requests from buyers'),
      code('  prices.js    -- Community market price board'),
      code('  wanted.js    -- Je Cherche buyer requests'),
      code('  admin.js     -- All admin panel actions'),
      code('  gemini.js    -- AI chat assistant (Google Gemini)'),
      br(),
      h2('The Client Folder (/client) -- The Frontend'),
      code('client/src/'),
      code('  App.jsx                   -- Main app, defines all pages and routes'),
      code('  main.jsx                  -- Entry point (first file the browser loads)'),
      code('  index.css                 -- All styling (colors, fonts, layouts)'),
      code(''),
      code('  components/               -- Reusable building blocks'),
      code('    Navbar.jsx              -- Top navigation bar on every page'),
      code('    ProductCard.jsx         -- One product tile shown in the grid'),
      code('    AvailabilityBadge.jsx   -- The Open/Away/Closed status badge'),
      code('    BendskinButton.jsx      -- The moto taxi delivery WhatsApp button'),
      code('    ChatWidget.jsx          -- Floating AI chat bubble'),
      code('    SafetyGate.jsx          -- Safety warning before contacting seller'),
      code('    WhatsAppButton.jsx      -- Green WhatsApp contact button'),
      code(''),
      code('  pages/                    -- Full pages that appear at specific URLs'),
      code('    Home.jsx                -- Homepage with products and stands grid'),
      code('    StandDetail.jsx         -- A vendor shop page'),
      code('    ProductDetail.jsx       -- Single product page with all features'),
      code('    Reels.jsx               -- Market Buzz (TikTok-style video feed)'),
      code('    PrixDuMarche.jsx        -- Community market price board'),
      code('    JeCherche.jsx           -- Buyer wanted board'),
      code('    Login.jsx, Register.jsx -- Auth pages'),
      code('    Profile.jsx             -- Edit name, bio, photo'),
      code('    Admin.jsx               -- Full admin panel (password protected)'),
      code(''),
      code('  context/                  -- Shared data accessible from any component'),
      code('    AuthContext.jsx         -- Stores who is logged in across the whole app'),
      code('    LanguageContext.jsx     -- Language (EN/FR) + all translations'),
      br(),
      pb(),

      /* ── CH 5 ── */
      h1('Chapter 5 -- Every Feature Explained'),

      h2('5.1  The Homepage -- Finding Products'),
      p('When you visit the website, the browser asks the backend for all products and stands. The backend queries the database and sends them back. The homepage shows: a hero banner, stats, a tab switcher (Products / Stands), region filter, category filter, and a search bar. All filters work instantly without any page reload.'),
      br(),

      h2('5.2  Stands -- Vendor Shops'),
      p('Every vendor can create one or more Stands. A stand contains the vendor name, description, city, phone number, all their products, contact buttons, availability status, and the Trusted Vendor badge if they have been verified.'),
      br(),

      h2('5.3  Products -- Listings'),
      p('Each product has a name, price in CFA, category, photo, and optionally a short video and a voice note from the seller. On the product detail page, buyers can contact the seller safely, bargain on price, arrange bendskin delivery, and request home delivery by filling a form with their exact location.'),
      br(),

      h2('5.4  The Bargain Calculator -- Negotiate Like at the Market'),
      p('In Cameroon, nobody pays the first price. Three offer levels appear on every product page:'),
      bullet('Cool (10% off) -- a polite, friendly offer'),
      bullet('Fair (20% off) -- a reasonable middle-ground offer'),
      bullet('Aggressive (30% off) -- pushing hard for the best deal'),
      p('Prices are automatically calculated from the listed price, rounded to the nearest 50 CFA. When the buyer taps an offer, a "Copy Message" button appears with a ready-to-send negotiation message in their language. They paste it into WhatsApp and send it to the vendor.'),
      br(),

      h2('5.5  The Bendskin Delivery Button'),
      p('After finding a product, the buyer clicks the orange Bendskin Delivery button. A panel opens asking for their delivery address. When they tap "Open WhatsApp", a pre-written message opens already filled with the product name, vendor, price, and the buyer\'s address. The buyer picks their bendskin rider from contacts and sends it. No new apps needed -- it uses WhatsApp that everyone already has.'),
      br(),

      h2('5.6  Market Buzz -- Short Video Reels'),
      p('Like TikTok, but for Cameroonian markets. Vendors post short videos showing their products. The layout has: a left panel with vendor info and "Visit Stand" button, the video in the center (tall, snap-scrolls into place), and action buttons on the right (like, shop, delete). Videos play automatically when scrolled into view.'),
      br(),

      h2('5.7  The Safety Gate'),
      p('Before showing any vendor\'s phone number, a safety reminder pops up: always meet in public, never pay before inspecting, use Mobile Money only after you have the item. This was built because mobile money scams are common in Cameroon.'),
      br(),

      h2('5.8  Trusted Vendor Badge (Commercant Certifie)'),
      p('A lion badge that appears next to a vendor\'s name everywhere on the site. The admin verifies a vendor by clicking "Verify" in the Admin Panel. The badge instantly appears on their stand, their products, and in Market Buzz. The lion was chosen because it is strong, trustworthy, and proudly Cameroonian.'),
      br(),

      h2('5.9  Vendor Availability Status (Statut du Stand)'),
      p('Every stand shows a colored status that tells buyers when the vendor is available: Open Now (green circle), Back Soon (yellow circle), or Closed (red circle). Vendors set this themselves by logging in and clicking one of the three status buttons on their stand page.'),
      br(),

      h2('5.10  Prix du Marche -- Community Price Board'),
      p('A live price board for 12 common Cameroonian market staples: Tomates, Plantains, Huile de palme, Riz blanc, Ndole, Boeuf, Poulet entier, Poisson fume, Manioc, Haricots, Piment rouge, Gombo. Anyone can submit what they paid today at which market in which city. The board shows Min, Average, and Max price per item from the last 24 hours. Prices reset every day.'),
      br(),

      h2('5.11  Je Cherche -- Buyer Wanted Board'),
      p('A reverse marketplace. Instead of sellers posting what they have, buyers post what they want -- for example "Looking for 20 kg of fresh groundnuts in Douala Akwa". Vendors browse the board and contact the buyer directly on WhatsApp. Posts expire automatically after 7 days. No login required.'),
      br(),

      h2('5.12  Bilingual Support (English and French)'),
      p('A language toggle button in the navigation bar switches the entire website between English and French instantly. All text is stored in a central translation file (LanguageContext.jsx). The choice is saved in the browser so it is remembered next time.'),
      br(),

      h2('5.13  AI Chat Assistant'),
      p('A floating chat bubble in the bottom-right corner of every page. Buyers can ask it anything about the market or products. It is powered by Google Gemini (Google\'s AI model). The question is sent to our backend which forwards it to Google Gemini, and the answer comes back and appears in the chat window.'),
      br(),
      pb(),

      /* ── CH 6 ── */
      h1('Chapter 6 -- The Admin Panel'),
      p('The Admin Panel is a password-protected control room accessed at the URL /admin. The default password is etoh_admin_2024 and can be changed in the .env file.'),
      br(),
      h2('Dashboard'),
      p('Shows total users, stands, products, reels, and orders. Stats auto-refresh every 30 seconds. Also shows the most recent orders with their status.'),
      br(),
      h2('Products'),
      p('Table of all products with search and category filter. Admin can edit any product (name, price, category, description, image, video) or delete it. The edit modal closes automatically after saving.'),
      br(),
      h2('Reels'),
      p('Grid of all Market Buzz reels. Admin can upload a new reel on behalf of any vendor, edit the title and description, or delete a reel.'),
      br(),
      h2('Stands'),
      p('Table of all stands. Admin can edit a stand (name, phone, city, description), give it the Trusted Vendor badge (Verify) or remove it, or delete the stand and all its products. Search by name, owner, or city.'),
      br(),
      h2('Orders'),
      p('All delivery requests. Admin can filter by status (Pending, Confirmed, Delivered, Cancelled), search by buyer or vendor, and update the status of any order using a dropdown -- the change saves instantly.'),
      br(),
      h2('Users'),
      p('All registered users. Admin can search by name, email, or WhatsApp number, and delete a user and all their data.'),
      br(),
      pb(),

      /* ── CH 7 ── */
      h1('Chapter 7 -- How Login and Security Work'),
      h2('Registration'),
      p('When someone signs up, the backend takes their password and runs it through a "hash" function (bcrypt). A hash turns "mypassword123" into a long unreadable string. Only the hash is saved to the database -- never the real password. Even if someone stole the database, they could not read anyone\'s password.'),
      br(),
      h2('Login'),
      p('The backend finds the account by email, uses bcrypt to check if the entered password matches the stored hash. If it matches, a JWT (JSON Web Token) is created -- a signed digital ticket. The token is sent to the browser and stored. For every future request that needs authentication, the browser sends this token. The backend checks it to know who is making the request.'),
      br(),
      h2('Admin Security'),
      p('The admin panel uses a secret password stored in the .env file. It is sent as a custom header (x-admin-key) with every admin request. The backend checks this header before allowing any admin action.'),
      br(),
      pb(),

      /* ── CH 8 ── */
      h1('Chapter 8 -- The API (How Parts Talk to Each Other)'),
      p('An API (Application Programming Interface) is like a waiter in a restaurant. The customer (frontend) tells the waiter (API) what they want. The waiter goes to the kitchen (backend + database), gets the data, and brings it back.'),
      br(),
      h2('Public Routes -- No Login Required'),
      code('GET  /api/stands             -- Get all stands'),
      code('GET  /api/stands/:id         -- Get one stand with its products'),
      code('GET  /api/products           -- Get all products'),
      code('GET  /api/products/:id       -- Get one product'),
      code('GET  /api/posts              -- Get all Market Buzz reels'),
      code('GET  /api/prices             -- Get today community price reports'),
      code('POST /api/prices             -- Submit a new price report'),
      code('GET  /api/wanted             -- Get all active buyer requests'),
      code('POST /api/wanted             -- Post a new buyer request'),
      code('DELETE /api/wanted/:id       -- Remove a buyer request'),
      br(),
      h2('Auth Routes'),
      code('POST /api/auth/register      -- Create a new account'),
      code('POST /api/auth/login         -- Log in and get a JWT token'),
      code('GET  /api/auth/me            -- Get my profile (requires token)'),
      code('PUT  /api/auth/profile       -- Update my profile (requires token)'),
      br(),
      h2('Protected Routes -- Login Required'),
      code('POST   /api/stands           -- Create a new stand'),
      code('PUT    /api/stands/:id       -- Edit my stand'),
      code('PUT    /api/stands/:id/availability -- Set my availability status'),
      code('DELETE /api/stands/:id       -- Delete my stand'),
      code('POST   /api/products         -- Add a product to my stand'),
      code('DELETE /api/products/:id     -- Delete my product'),
      code('POST   /api/posts            -- Post a Market Buzz reel'),
      code('POST   /api/orders           -- Place a delivery order'),
      br(),
      h2('Admin Routes -- Admin Key Required'),
      code('GET  /api/admin/stats               -- Dashboard statistics'),
      code('GET  /api/admin/orders              -- All orders'),
      code('PUT  /api/admin/orders/:id/status   -- Update order status'),
      code('GET  /api/admin/products            -- All products'),
      code('PUT  /api/admin/products/:id        -- Edit any product'),
      code('DELETE /api/admin/products/:id      -- Delete any product'),
      code('GET  /api/admin/stands              -- All stands with owner info'),
      code('PUT  /api/admin/stands/:id/edit     -- Edit any stand'),
      code('PUT  /api/admin/stands/:id/verify   -- Verify a stand'),
      code('DELETE /api/admin/stands/:id        -- Delete any stand'),
      code('GET  /api/admin/users               -- All users'),
      code('DELETE /api/admin/users/:id         -- Delete any user'),
      br(),
      pb(),

      /* ── CH 9 ── */
      h1('Chapter 9 -- How to Run the Project'),
      h2('What You Need First'),
      bullet('Node.js (version 18 or higher) -- download from nodejs.org'),
      bullet('A code editor like VS Code'),
      bullet('A terminal (Command Prompt, PowerShell, or Git Bash)'),
      br(),
      h2('Step 1: Install Backend Dependencies'),
      code('cd etoh_market'),
      code('npm install'),
      br(),
      h2('Step 2: Install Frontend Dependencies'),
      code('cd client'),
      code('npm install'),
      code('cd ..'),
      br(),
      h2('Step 3: Seed the Database with Sample Data (Optional)'),
      code('node seed.js'),
      code('node seed_prices.js'),
      br(),
      h2('Step 4: Start the Backend Server'),
      code('node server.js'),
      p('You should see: "ETOH Market Server -> http://localhost:3000"'),
      br(),
      h2('Step 5: Start the Frontend (in a second terminal)'),
      code('cd client'),
      code('npm run dev'),
      p('You should see: "Local: http://localhost:5173"'),
      br(),
      h2('Step 6: Open the Website'),
      bullet('Main site:     http://localhost:5173'),
      bullet('Admin panel:   http://localhost:5173/admin  (password: etoh_admin_2024)'),
      bullet('Market Buzz:   http://localhost:5173/market-buzz'),
      bullet('Price Board:   http://localhost:5173/prix-du-marche'),
      bullet('Buyer Board:   http://localhost:5173/je-cherche'),
      br(),
      pb(),

      /* ── CH 10 ── */
      h1('Chapter 10 -- Technology Used and Why'),
      h2('Backend'),
      bullet('Node.js -- JavaScript on the server. Same language as the frontend, easier to maintain.'),
      bullet('Express.js -- The most popular, simplest way to build APIs in Node.js.'),
      bullet('SQLite -- A single-file database. No installation needed, no separate server. Perfect for this size. Can be upgraded to PostgreSQL later.'),
      bullet('bcryptjs -- Industry-standard password hashing. Slow by design to stop brute-force attacks.'),
      bullet('jsonwebtoken (JWT) -- Stateless authentication. The token carries all login info so the server does not need to remember sessions.'),
      bullet('multer -- Handles file uploads (images and videos) cleanly.'),
      bullet('dotenv -- Loads secret settings from .env without hardcoding sensitive values.'),
      br(),
      h2('Frontend'),
      bullet('React -- Component-based UI. Every card, button, and modal is a reusable component.'),
      bullet('Vite -- 100x faster than old tools. Makes development fast and production builds small.'),
      bullet('React Router -- Navigation between pages without full page reloads. Feels instant.'),
      bullet('Axios -- Clean HTTP client for API requests with better error handling than native fetch.'),
      bullet('React Context API -- Shares login state and language across the whole app without prop drilling.'),
      br(),
      h2('External Services'),
      bullet('Google Gemini AI -- Powers the AI chat assistant.'),
      bullet('WhatsApp (wa.me links) -- All buyer-seller communication. No new infrastructure -- everyone in Cameroon already uses it.'),
      br(),
      pb(),

      /* ── CH 11 ── */
      h1('Chapter 11 -- Testing'),
      p('The project includes automated tests in the /tests folder. Run them with:'),
      code('npm test'),
      br(),
      h2('What the Tests Check'),
      bullet('Smoke tests -- Does every API route respond without crashing?'),
      bullet('Auth tests -- Can users register, log in, and access protected routes correctly?'),
      bullet('User story tests -- Does the full flow work end-to-end? Register -> Create stand -> Add product -> Place order'),
      bullet('QA tests -- Are error messages correct? Are invalid inputs rejected?'),
      br(),
      p('Tests use Jest (test runner) and Supertest (sends real HTTP requests). They run against an isolated test database that is wiped after each run -- never touching the real etoh.db.'),
      br(),
      pb(),

      /* ── CH 12 ── */
      h1('Chapter 12 -- Design Principles'),
      p('Every design decision was guided by one question: "Will this work for someone in Cameroon on a basic Android phone with a slow internet connection?"'),
      br(),
      h2('Speed Over Everything'),
      bullet('The backend sends only the data needed -- no giant responses'),
      bullet('Images are stored locally (no expensive external CDNs)'),
      bullet('React updates only what changed on screen -- no full page reloads'),
      br(),
      h2('WhatsApp First'),
      p('WhatsApp is how Cameroonians do business. Every contact button, delivery request, and bargain offer connects through WhatsApp. We do not try to replace a tool that already works.'),
      br(),
      h2('No Payment Integration'),
      p('ETOH Market deliberately does not process payments. The platform connects buyers and sellers, but money changes hands outside -- in person, via Mobile Money, or through a trusted arrangement. This eliminates fraud risk and keeps the platform simple.'),
      br(),
      h2('Bilingual from Day One'),
      p('Cameroon is officially bilingual. All labels are stored in a central translation file and both languages are always in sync. Switching takes one click.'),
      br(),
      h2('Community-Powered'),
      bullet('Prix du Marche -- every price report makes the board more accurate for everyone'),
      bullet('Je Cherche -- buyers and vendors connect without us in the middle'),
      bullet('Market Buzz -- vendors market themselves directly to buyers'),
      br(),
      pb(),

      /* ── CH 13 ── */
      h1('Chapter 13 -- Future Ideas'),
      h2('Short Term'),
      bullet('Push notifications -- alert a buyer when a followed vendor posts a new reel'),
      bullet('Product reviews -- buyers leave text testimonials on products they purchased'),
      bullet('Group buy (Tontine) -- multiple buyers pool together for a bulk discount'),
      bullet('Vendor analytics -- show each vendor how many people viewed their stand this week'),
      br(),
      h2('Medium Term'),
      bullet('Mobile app (React Native) -- same codebase adapted for Android and iPhone'),
      bullet('Orange Money / MTN MoMo fees display -- show buyers the exact total including transfer fees'),
      bullet('Multi-language support -- add Pidgin English, Fulfulde, Bassa, Ewondo'),
      bullet('Seller ratings -- a trust score built from buyer feedback'),
      br(),
      h2('Long Term'),
      bullet('Verified delivery network -- partner with bendskin associations for tracked delivery'),
      bullet('Wholesale marketplace -- bulk orders for restaurants, caterers, and event planners'),
      bullet('ETOH Finance -- micro-credit for vendors who need to buy stock upfront'),
      br(),
      pb(),

      /* ── CLOSING ── */
      h1('Final Words'),
      p('ETOH Market started with a simple idea: Cameroon has some of the most talented, hardworking vendors in the world. They deserve a digital home that is as vibrant, practical, and community-centered as the markets they run every day.'),
      br(),
      p('Every line of code in this project was written with that in mind. Every feature solves a real problem. Every button was designed for someone on a phone in Douala, Yaounde, Bamenda, or any corner of Cameroon.'),
      br(),
      p('This is not just a marketplace. It is a digital Marche Central -- where commerce, community, and Cameroonian spirit come together.'),
      br(),
      new Paragraph({
        children: [new TextRun({ text: 'Built with love for Cameroon.', bold: true, size: 32, font: 'Calibri', color: '92400e' })],
        alignment: AlignmentType.CENTER,
        spacing: { before: 400 },
      }),
    ],
  }],
});

Packer.toBuffer(doc).then(buf => {
  fs.writeFileSync('ETOH_Market_Documentation.docx', buf);
  console.log('Documentation generated: ETOH_Market_Documentation.docx (' + (buf.length / 1024).toFixed(1) + ' KB)');
});
